apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
    - name: nginx
      image: nginx:1.18-alpine
    - name: debian
      image: debian:buster-slim
      command: ["sleep", "600"]