apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-configmap
spec:
  containers:
    - name: demo-configmap
      image: alpine:3.9
      command:
        - "sleep"
        - "10000"
      env:
        - name: FORMATION
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: formation          
