---
version: '2.4'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - "./html:/usr/share/nginx/html"
    - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
  
  php:
    image: php_mysql
    volumes:
      - "./html:/srv/http"
    ports:
      - 9000:9000