apiVersion: apps/v1
kind: Deployment                     # Ressource de type deploy
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 3                        # Ressource Replicaset
  selector:
    matchLabels:
      app: frontend
  template:                          # Ressource POD 
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bilbloke/frontend:1.0